// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function LoadTodos():Promise<Array<models.Todo>>;

export function SaveTodos(arg1:Array<models.Todo>):Promise<void>;
