// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadTodos() {
  return window['go']['main']['App']['LoadTodos']();
}

export function SaveTodos(arg1) {
  return window['go']['main']['App']['SaveTodos'](arg1);
}
