// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTodo(arg1:string):Promise<models.Todo>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetTodos():Promise<Array<models.Todo>>;

export function SaveTodos(arg1:Array<models.Todo>):Promise<void>;

export function ToggleTodo(arg1:number):Promise<void>;
